spring:
  data:
    postgres:
      host: ~ # profile override
      port: ~ # profile override
      database: ~ # profile override
      username: ~ # profile override
      password: ~ # profile override
