tankerkoenig:
  api:
    url: https://creativecommons.tankerkoenig.de
    api-key: ***REMOVED***
    timeout: 30s
    retry-attempts: 3

scheduler:
  initial-delay: 10s
  delay: 10m

coroutines:
  dispathcer:
    threads: 4

area:
  lat: ~ # profile override
  lon: ~ # profile override
  radius: ~ # profile override

spring:
  data:
    postgres:
      host: ~ # profile override
      port: ~ # profile override
      database: ~ # profile override
      username: ~ # profile override
      password: ~ # profile override

